# Generated by Django 4.2.3 on 2023-10-09 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=300)),
                ('segment_id', models.UUIDField()),
                ('is_audience_refresh', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(choices=[('PUBLISH_JOB', 'PUBLISH_JOB')], max_length=100)),
                ('resource_id', models.UUIDField()),
                ('resource_action_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('raw_data', models.JSONField()),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_system_action', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTriggerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('job_run_status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='RUNNING', max_length=50)),
                ('platform_config', models.JSONField()),
                ('error', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audience.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPlatformMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('META', 'META'), ('TIKTOK', 'TIKTOK'), ('PINTEREST', 'PINTEREST'), ('SNAPCHAT', 'SNAPCHAT'), ('ADELPHIC', 'ADELPHIC'), ('AMAZON', 'AMAZON'), ('THE_TRADE_DESK', 'THE_TRADE_DESK'), ('TWITTER', 'TWITTER'), ('YAHOO', 'YAHOO'), ('DV360', 'DV360'), ('JUN_GROUP', 'JUN_GROUP'), ('LINKEDIN', 'LINKEDIN'), ('MICROSOFT_BING', 'MICROSOFT_BING'), ('ROKU', 'ROKU'), ('SAMSUNG_ADS', 'SAMSUNG_ADS'), ('WALMART', 'WALMART')], max_length=50)),
                ('upload_type', models.CharField(choices=[('DMO', 'DMO'), ('DMP', 'DMP')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PUBLISHED', 'PUBLISHED'), ('ERRORED', 'ERRORED')], default='PENDING', max_length=50)),
                ('is_retryable', models.BooleanField(default=False)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audience.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('segment_id', 'job_name'), name='UniqueSegmentJob'),
        ),
        migrations.AddConstraint(
            model_name='jobplatformmapping',
            constraint=models.UniqueConstraint(fields=('job', 'platform'), name='UniqueJobPlatform'),
        ),
    ]
